# Лабораторная работа №1
## Задание
Средствами numpy сгенерировать две матрицы и найти индексы одинаковых элементов

## Решение
Генерация матриц:

In [8]:
import numpy as np
import pandas as pd

rnd = np.random.default_rng()
size_col = np.random.randint(10, 20)
size_row = np.random.randint(10, 20)

matrix1 = rnd.integers(0, 50, (size_row, size_col))
matrix2 = rnd.integers(0, np.amax(matrix1), (size_row, size_col))

df = pd.DataFrame(matrix1)
df.style.set_caption("Матрица 1").set_table_styles([{'selector': 'th', 'props': [('background-color', '#f0f0f0')]}])
df

0   1   2   3   4   5   6   7   8   9   10  11  12
0   47  25   6  13  45   2  20   1  47  49  39   4  22
1   26  11  12   5  19  38   8  20   7  48  11  39  49
2   10  43  24  17  23  29  43  11  26  29   6   0   9
3    5  38  48  16  29  19  15  10  14  22  35  27  27
4   26  35   5  45   3  30  25  44  42  26  40   4  42
5   17  37   5   2   1  12  29  39   4  20  42   7  12
6   36  24  20  28  44  42   0   8   7  25   7  27  30
7   26  10  22  14  48  34  40  43  46  44  28  30  40
8   29  39  11  40  31  44   3   5  35  15  19  44  15
9   10  48  30   4   8  34  22  32   1  14  18  13  15
10  38  37  21   8  43  12  44  18   3  24  28  42   1

In [9]:
df = pd.DataFrame(matrix2)
df.style.set_caption("Матрица 2").set_table_styles([{'selector': 'th', 'props': [('background-color', '#f0f0f0')]}])
df

0   1   2   3   4   5   6   7   8   9   10  11  12
0   24  41  30  43   5  21   5  23  43  44  22   3   3
1   28  45  32  43  33   0   1  15  17  46   5   7  13
2    3  15   1  12  16   6  36   2  28  18  26  32   3
3   46  14   2  35  19  25  28  47  33  12  32  17  44
4   40  24  11  47  47  13  45  29  36  25  28   9  13
5   46   6  32  37  37  34  25  29  23   5   4  43   7
6   33  16  11  32  34  24   3   2   0  15  31  37   4
7   42   6  45  21  40  20  36  39   3  33  45  37  22
8   19  13   9  42  28   5  37  37  45  30  35  48  45
9    9   1  17  46  45  46   6  40  18   0  43   6  23
10  22   3  29   7  43  27  29  31  34  19   9   4  10

Поиск элементов, совпадающих по позиции и значению, и вывод индексов одинаковых элементов:

In [10]:
#значения элементов в res: true - на месте одинаковых элементов, false - на месте разных элементов
res = (matrix1 == matrix2)
indices = np.argwhere(res)

if (indices.size == 0):
  print ("В этот раз с одинаковыми элементами не повезло. Их нет")
else:
  print("Индексы одинаковых элементов: \n", indices)

Индексы одинаковых элементов: 
 [[10  4]]


Поиск совпадающих элементов в первой и второй матрице




In [13]:
check = np.zeros_like(matrix1, dtype=bool)
for i in range(size_row):
    for j in range(size_col):
        if (check[i][j] == False):
            cur = matrix1[i, j]
        else:
            break
        #найти все одинаковые элементы в первом массиве
        indices1 = np.argwhere(matrix1 == cur)
        #выставить в true для всех одинаковых элементов
        for k in indices1:
            check[k[0]][k[1]] = True

        indices2 = np.argwhere(matrix2 == cur)
        if (indices2.size == 0):
            print("\n\nДля элемента первой матрицы со значением ", cur, " совпадений не найдено")
        else:
            print("\n\nВ первой матрице значение ", cur, " имеют элементы со следующими индексами:\n", indices1)
            print("Такое же значение во второй матрице имеют элементы с индексами:\n", indices2)



В первой матрице значение  47  имеют элементы со следующими индексами:
 [[0 0]
 [0 8]]
Такое же значение во второй матрице имеют элементы с индексами:
 [[3 7]
 [4 3]
 [4 4]]


В первой матрице значение  25  имеют элементы со следующими индексами:
 [[0 1]
 [4 6]
 [6 9]]
Такое же значение во второй матрице имеют элементы с индексами:
 [[3 5]
 [4 9]
 [5 6]]


В первой матрице значение  6  имеют элементы со следующими индексами:
 [[ 0  2]
 [ 2 10]]
Такое же значение во второй матрице имеют элементы с индексами:
 [[ 2  5]
 [ 5  1]
 [ 7  1]
 [ 9  6]
 [ 9 11]]


В первой матрице значение  13  имеют элементы со следующими индексами:
 [[ 0  3]
 [ 9 11]]
Такое же значение во второй матрице имеют элементы с индексами:
 [[ 1 12]
 [ 4  5]
 [ 4 12]
 [ 8  1]]


В первой матрице значение  45  имеют элементы со следующими индексами:
 [[0 4]
 [4 3]]
Такое же значение во второй матрице имеют элементы с индексами:
 [[ 1  1]
 [ 4  6]
 [ 7  2]
 [ 7 10]
 [ 8  8]
 [ 8 12]
 [ 9  4]]


В первой матрице значен